<a href="https://colab.research.google.com/github/Esaiasson/Machine_learning_WS_2025/blob/pre_processing_amazon/A1/amazon_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import of the neccesary libraries

In [10]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [11]:
folder = ""
reviews_learn_dataset_path = folder + "amazon_review_ID.shuf.lrn.csv"
reviews_test_dataset_path = folder + "amazon_review_ID.shuf.tes.csv"

Reading in the CSV-file.

In [12]:
rev_df_lrn_original = pd.read_csv(reviews_learn_dataset_path)
rev_df_tes_original = pd.read_csv(reviews_test_dataset_path)

rev_df_lrn = rev_df_lrn_original.copy()
rev_df_tes = rev_df_tes_original.copy()

print("Train dataset")
print(rev_df_lrn.head())

print("Test dataset")
print(rev_df_tes.head())

Train dataset
   ID  V1  V2  V3  V4  V5  V6  V7  V8  V9  ...  V9992  V9993  V9994  V9995  \
0   0  17   4   8   8   9   4   0   2   3  ...      0      0      0      0
1   1  21   9   5   8   6   2  16   3  12  ...      0      0      0      2
2   2   9   7   6   3   8   2   9   4   4  ...      0      0      0      0
3   3   8   3   5   2   4   3   8   2   4  ...      0      0      1      0
4   4  15   8   8   4   7   8   4   7   1  ...      0      0      0      0

   V9996  V9997  V9998  V9999  V10000    Class
0      0      0      0      1       1     Shea
1      2      1      0      1       0    Riley
2      0      0      0      1       1  Chachra
3      1      0      0      0       0  Agresti
4      0      0      0      0       0    Nigam

[5 rows x 10002 columns]
Test dataset
    ID  V1  V2  V3  V4  V5  V6  V7  V8  V9  ...  V9991  V9992  V9993  V9994  \
0  750  23   6   4   7  11   0   5   2   6  ...      0      0      1      0
1  751  20  12  15   6   9  14   2   6   2  ...      1      3      0      0
2  752  13  10  10   5  12   5   3   4   5  ...      1      0      1      0
3  753  14  15   6   1   7   2   7   2   5  ...      0      0      1      2
4  754   9   8   3   4  10   3   2   2   1  ...      0      0      0      0

   V9995  V9996  V9997  V9998  V9999  V10000
0      0      0      0      0      0       0
1      0      0      0      0      0       0
2      0      0      1      0      1       1
3      0      2      1      0      1       0
4      0      0      0      0      1       0

[5 rows x 10001 columns]

Some basic information about the dataset

In [13]:
def dataset_info(df, split_type):
  shape = df.shape
  print("The dataset consists of: " + str(shape[0]) +  " rows and " + str(shape[1]) + " columns")
  if split_type == "train":
    unique_values = df['Class'].unique()
    print("The dataset has " + str(len(unique_values)) + " unique values in the target attribute")
    print("The values are: ")
    print(unique_values)
  print("\n")

  na_col = df.isna().sum()
  if na_col[na_col > 0].shape == (0,):
      print("There are no missing values in the dataset")
  else:
    print("The columns with NA values are: ")
    na_col[na_col > 0]

  print("\n")
  d_types = pd.Series(df.dtypes)
  print("The datatypes in the frame are:")
  print(d_types.value_counts())

In [14]:
print("Training dataset information: ")
print("\n")
dataset_info(rev_df_lrn, "train")
print("\n")
print("Test dataset information: ")
print("\n")
dataset_info(rev_df_tes, "test")

Training dataset information:


The dataset consists of: 750 rows and 10002 columns
The dataset has 50 unique values in the target attribute
The values are:
['Shea' 'Riley' 'Chachra' 'Agresti' 'Nigam' 'Messick' 'Cutey' 'Mitchell'
 'Ashbacher' 'Brody' 'Vernon' 'Goonan' 'Harp' 'Lovitt' 'Corn' 'Engineer'
 'Calvinnme' 'Chell' 'Comdet' 'Kolln' 'Peterson' 'Dent' 'Wilson' 'Mark'
 'Grove' 'Janson' 'Brown' 'Auken' 'Sherwin' 'Cholette' 'McKee' 'Taylor'
 'Walters' 'Merritt' 'Blankenship' 'Chandler' 'Johnson' 'Hayes' 'Koenig'
 'CFH' 'Lawyeraau' 'Davisson' 'Mahlers2nd' 'Power' 'Robert' 'Morrison'
 'Lee' 'Neal' 'Bukowsky' 'Vision']


There are no missing values in the dataset


The datatypes in the frame are:
int64     10001
object        1
Name: count, dtype: int64


Test dataset information:


The dataset consists of: 750 rows and 10001 columns


There are no missing values in the dataset


The datatypes in the frame are:
int64    10001
Name: count, dtype: int64

To be able to work with target attributes in a classification task, we need a numeric representation of the different classes.
Therefore we encode the different text categories with a numeric representation.

It isn't strictly neccesary to encode the classes in the target attribute numericaly, in terms of the theory beind classification algorithms, but most frameworks require a numerical representation since it makes comparisons and storage more efficient.

To do this, SKLearns preprocessing library is used, and the orignal categorires are stored in a variable

In [15]:
le = LabelEncoder()

rev_df_lrn['Class'] = rev_df_lrn['Class'].astype('category')
rev_df_lrn_text_categories = rev_df_lrn['Class'].astype('category')
rev_df_lrn['Class_encoded'] = le.fit_transform(rev_df_lrn['Class'])
rev_df_lrn['Class_encoded'] = rev_df_lrn['Class_encoded'].astype('category')

le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print("The characters encodings are: ")
print(le_name_mapping)

print("Dataframe after class encoding: ")
rev_df_lrn = rev_df_lrn.drop('Class', axis=1)

rev_df_lrn.head()

The characters encodings are:
{'Agresti': np.int64(0), 'Ashbacher': np.int64(1), 'Auken': np.int64(2), 'Blankenship': np.int64(3), 'Brody': np.int64(4), 'Brown': np.int64(5), 'Bukowsky': np.int64(6), 'CFH': np.int64(7), 'Calvinnme': np.int64(8), 'Chachra': np.int64(9), 'Chandler': np.int64(10), 'Chell': np.int64(11), 'Cholette': np.int64(12), 'Comdet': np.int64(13), 'Corn': np.int64(14), 'Cutey': np.int64(15), 'Davisson': np.int64(16), 'Dent': np.int64(17), 'Engineer': np.int64(18), 'Goonan': np.int64(19), 'Grove': np.int64(20), 'Harp': np.int64(21), 'Hayes': np.int64(22), 'Janson': np.int64(23), 'Johnson': np.int64(24), 'Koenig': np.int64(25), 'Kolln': np.int64(26), 'Lawyeraau': np.int64(27), 'Lee': np.int64(28), 'Lovitt': np.int64(29), 'Mahlers2nd': np.int64(30), 'Mark': np.int64(31), 'McKee': np.int64(32), 'Merritt': np.int64(33), 'Messick': np.int64(34), 'Mitchell': np.int64(35), 'Morrison': np.int64(36), 'Neal': np.int64(37), 'Nigam': np.int64(38), 'Peterson': np.int64(39), 'Power': np.int64(40), 'Riley': np.int64(41), 'Robert': np.int64(42), 'Shea': np.int64(43), 'Sherwin': np.int64(44), 'Taylor': np.int64(45), 'Vernon': np.int64(46), 'Vision': np.int64(47), 'Walters': np.int64(48), 'Wilson': np.int64(49)}
Dataframe after class encoding:

,ID,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V9992,V9993,V9994,V9995,V9996,V9997,V9998,V9999,V10000,Class_encoded
0,0,17,4,8,8,9,4,0,2,3,...,0,0,0,0,0,0,0,1,1,43
1,1,21,9,5,8,6,2,16,3,12,...,0,0,0,2,2,1,0,1,0,41
2,2,9,7,6,3,8,2,9,4,4,...,0,0,0,0,0,0,0,1,1,9
3,3,8,3,5,2,4,3,8,2,4,...,0,0,1,0,1,0,0,0,0,0
4,4,15,8,8,4,7,8,4,7,1,...,0,0,0,0,0,0,0,0,0,38

Some model really on meassuring the numeric distance between samples, and there the value range should not have an impact. To not let the value range have an impact, the data can be scaled.

There are several ways to do this, here the values will be adjusted using min-max scaling and the z-score method.

Min max scaling:

In [36]:
rev_df_lrn_minmax_scaled = rev_df_lrn.copy()
rev_df_tes_minmax_scaled = rev_df_tes.copy()


for column in rev_df_lrn_minmax_scaled.iloc[:, 1:10001].columns:
    rev_df_lrn_minmax_scaled[column] = (rev_df_lrn_minmax_scaled[column] - rev_df_lrn_minmax_scaled[column].min()) / (rev_df_lrn_minmax_scaled[column].max() - rev_df_lrn_minmax_scaled[column].min())

for column in rev_df_tes_minmax_scaled.iloc[:, 1:10001].columns:
    rev_df_tes_minmax_scaled[column] = (rev_df_tes_minmax_scaled[column] - rev_df_tes_minmax_scaled[column].min()) / (rev_df_tes_minmax_scaled[column].max() - rev_df_tes_minmax_scaled[column].min())



rev_df_lrn_minmax_scaled.head()

,ID,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V9991,V9992,V9993,V9994,V9995,V9996,V9997,V9998,V9999,V10000
0,750,0.71875,0.285714,0.210526,0.28,0.458333,0.000000,0.25,0.133333,0.545455,...,0.00,0.0,0.25,0.0,0.0,0.0,0.00,0.0,0.000000,0.00
1,751,0.62500,0.571429,0.789474,0.24,0.375000,1.000000,0.10,0.400000,0.181818,...,0.25,0.5,0.00,0.0,0.0,0.0,0.00,0.0,0.000000,0.00
2,752,0.40625,0.476190,0.526316,0.20,0.500000,0.357143,0.15,0.266667,0.454545,...,0.25,0.0,0.25,0.0,0.0,0.0,0.25,0.0,0.333333,0.25
3,753,0.43750,0.714286,0.315789,0.04,0.291667,0.142857,0.35,0.133333,0.454545,...,0.00,0.0,0.25,0.5,0.0,0.5,0.25,0.0,0.333333,0.00
4,754,0.28125,0.380952,0.157895,0.16,0.416667,0.214286,0.10,0.133333,0.090909,...,0.00,0.0,0.00,0.0,0.0,0.0,0.00,0.0,0.333333,0.00

Z-score standardisation:

In [38]:
rev_df_lrn_z_scaled = rev_df_lrn.copy()
rev_df_tes_z_scaled = rev_df_tes.copy()


for column in rev_df_lrn_z_scaled.iloc[:, 1:10001].columns:
    rev_df_lrn_z_scaled[column] = (rev_df_lrn_z_scaled[column] - rev_df_lrn_z_scaled[column].mean()) / rev_df_lrn_z_scaled[column].std()

for column in rev_df_tes_z_scaled.iloc[:, 1:10001].columns:
    rev_df_tes_z_scaled[column] = (rev_df_tes_z_scaled[column] - rev_df_tes_z_scaled[column].mean()) / rev_df_tes_z_scaled[column].std()


rev_df_lrn_z_scaled.head()

,ID,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V9992,V9993,V9994,V9995,V9996,V9997,V9998,V9999,V10000,Class_encoded
0,0,0.993257,-0.942116,0.383131,0.436613,0.857942,-0.198186,-0.978426,-0.669824,0.023201,...,-0.346017,-0.413466,-0.303511,-0.369314,-0.446316,-0.415482,-0.424824,1.684608,1.348931,43
1,1,1.730642,0.477874,-0.517647,0.436613,-0.051323,-0.904310,2.953629,-0.241182,4.144396,...,-0.346017,-0.413466,-0.303511,3.299365,3.515066,1.763619,-0.424824,1.684608,-0.371644,41
2,2,-0.481512,-0.090122,-0.217388,-0.915409,0.554853,-0.904310,1.233355,0.187459,0.481111,...,-0.346017,-0.413466,-0.303511,-0.369314,-0.446316,-0.415482,-0.424824,1.684608,1.348931,9
3,3,-0.665859,-1.226115,-0.517647,-1.185814,-0.657499,-0.551248,0.987601,-0.669824,0.481111,...,-0.346017,-0.413466,1.004726,-0.369314,1.534375,-0.415482,-0.424824,-0.442422,-0.371644,0
4,4,0.624565,0.193876,0.383131,-0.645005,0.251765,1.214064,0.004587,1.473384,-0.892620,...,-0.346017,-0.413466,-0.303511,-0.369314,-0.446316,-0.415482,-0.424824,-0.442422,-0.371644,38

FOR LATER!
Transforming the encoded class labels back to the original labels

In [43]:
def decode_classes(df):
  de_coded = df.copy()

  de_coded['Class'] = le.inverse_transform(de_coded['Class_encoded'])

  print(de_coded.head())